# Generated by Django 6.0.5 on 2026-06-30 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='expertise',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='core.expertise'),
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='core.expertise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('lieu', models.CharField(blank=True, default='', max_length=120)),
                ('year', models.CharField(blank=True, default='', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='realisations/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to='core.expertise')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
