# Generated by Django 6.0.5 on 2026-08-09 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_populate_expertise_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=80, verbose_name='Marque')),
                ('model', models.CharField(max_length=80, verbose_name='Modèle')),
                ('year', models.CharField(blank=True, default='', max_length=10, verbose_name='Année')),
                ('price_day', models.PositiveIntegerField(default=0, verbose_name='Prix / jour')),
                ('price_week', models.PositiveIntegerField(default=0, verbose_name='Prix / semaine')),
                ('price_month', models.PositiveIntegerField(default=0, verbose_name='Prix / mois')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('chauffeur', models.CharField(choices=[('deux', 'Avec ou sans chauffeur'), ('avec', 'Avec chauffeur uniquement'), ('sans', 'Sans chauffeur uniquement')], default='deux', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicules/', verbose_name='Photo principale')),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='core.expertise')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('avec_chauffeur', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('confirmée', 'Confirmée'), ('terminée', 'Terminée'), ('annulée', 'Annulée')], default='nouvelle', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='core.vehicule')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VehiculePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicules/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.vehicule')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
