# Generated by Django 6.0.5 on 2026-08-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vehicule_tarifs_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationImmigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('pays', models.CharField(max_length=40, verbose_name='Destination')),
                ('motif', models.CharField(max_length=20, verbose_name='Objectif')),
                ('score', models.PositiveIntegerField(default=0)),
                ('verdict', models.CharField(blank=True, default='', max_length=40)),
                ('reponses', models.JSONField(blank=True, default=dict)),
                ('points_faibles', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('contactee', 'Contactée'), ('accompagnee', 'En accompagnement'), ('close', 'Close')], default='nouvelle', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Évaluation immigration',
                'verbose_name_plural': 'Évaluations immigration',
                'ordering': ['-created'],
            },
        ),
    ]
