# Generated by Django 6.0.5 on 2026-08-14 08:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_evaluationimmigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='ville',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Ville'),
        ),
        migrations.CreateModel(
            name='VehiculeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='vehicules/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg', 'mov', 'm4v'])], verbose_name='Vidéo')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='vehicules/', verbose_name='Vignette')),
                ('order', models.PositiveIntegerField(default=0)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.vehicule')),
            ],
            options={
                'verbose_name': 'Vidéo de véhicule',
                'verbose_name_plural': 'Vidéos de véhicule',
                'ordering': ['order', 'id'],
            },
        ),
    ]
