# Generated by Django 6.0.5 on 2026-08-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vehicule_ville_vehiculevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaysImmigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.SlugField(max_length=40, unique=True, verbose_name='Clé du barème')),
                ('nom', models.CharField(max_length=80, verbose_name='Pays')),
                ('ouvert', models.BooleanField(default=True, verbose_name='Destination ouverte')),
                ('message', models.CharField(blank=True, default='', max_length=200, verbose_name='Motif de la fermeture')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Destination immigration',
                'verbose_name_plural': 'Destinations immigration',
                'ordering': ['order', 'nom'],
            },
        ),
    ]
